# Generated by Django 4.0.1 on 2022-02-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsstory_category_newsstory_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='category',
            field=models.CharField(choices=[('MISC', 'Misc'), ('TRAVELS', 'Travels'), ('CODING', 'Coding')], default='Misc', max_length=200),
        ),
    ]
